openapi: "3.0.0"
info:
  description: "This is the documentation on how to use our API's"
  version: "1.0.0"
  title: "Chit Chat API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: Steven Tran
    email: steventt07@gmail.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://dev.chitchat.com/v1
    description: Dev Server

paths:
  /feed:
    get:
      description: fetch feed information
      parameters: 
        - name: bodyLimit
          in: query
          description: The amount of posts returned
          schema:
            type: integer
            minimum: 10
            maximum: 20
            example: 15
        - name: pageLimit
          in: query
          description: The pages to return feed info 
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 2
      responses:
        200:
          description: Successful pull of feed info
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: steventt07
                    content: 
                      type: string
                      example: my first post
                    zipcode:
                      type: integer
                      example: 75094
                    comments:
                      type: array
                      items:
                        properties:
                          id:
                            type: integer
                            example: 1
  /catergory:
    get:
      description: fetch catergory information
      parameters: 
        - name: catergory
          in: query
          description: Name of catergory
          schema:
            type: string
            example: Deals
        - name: bodyLimit
          in: query
          description: The amount of posts returned
          schema:
            type: integer
            minimum: 10
            maximum: 20
            example: 15
        - name: pageLimit
          in: query
          description: The pages to return category info 
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 2
      responses:
        200:
          description: Successful pull of catergory info
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: steventt07
                    content: 
                      type: string
                      example: my first post
                    zipcode:
                      type: integer
                      example: 75094
                    comments:
                      type: array
                      items:
                        properties:
                          id:
                            type: integer
                            example: 1
  /add_post_to_category:
    post:
      description: Add a post to a category
      requestBody:
        required: true
        content: 
          application/json: 
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                catergory:
                  type: string
                  example: Deals
                username:
                  type: string
                  example: steventt07
                content: 
                  type: string
                  example: my first post
                zipcode:
                  type: integer
                  example: 75094
      responses:
        200:
          description: Successfully added a post to a category
          
  /remove_post_to_category:
    post:
      description: Remove a post from a category
      requestBody:
        required: true
        content: 
          application/json: 
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                catergory:
                  type: string
                  example: Deals
      responses:
        200:
          description: Successfully removed a post from a category
                
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
            